//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.0
//     from Assets/Scripts/ActiveBattlesSystem/ActiveBattleInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ActiveBattleInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ActiveBattleInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ActiveBattleInput"",
    ""maps"": [
        {
            ""name"": ""ActiveBattle"",
            ""id"": ""cea2a61a-925f-4fb4-ae08-4d7cb635ced2"",
            ""actions"": [
                {
                    ""name"": ""One"",
                    ""type"": ""Button"",
                    ""id"": ""ee631811-2891-424f-aa43-eb6a7ffd00cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Two"",
                    ""type"": ""Button"",
                    ""id"": ""8eb8e97b-388d-4e60-bca6-7e7fa69c0f27"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Three"",
                    ""type"": ""Button"",
                    ""id"": ""e0235be8-8635-4738-966d-ed43b25c38c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Four"",
                    ""type"": ""Button"",
                    ""id"": ""f9fbbd60-bbf0-485b-8bba-90dd9d6f1467"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Five"",
                    ""type"": ""Button"",
                    ""id"": ""33d2fa91-f98a-4b70-b6dd-15c613724a8e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Six"",
                    ""type"": ""Button"",
                    ""id"": ""b39d8943-0de1-452e-acb7-693c1fa725c2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Seven"",
                    ""type"": ""Button"",
                    ""id"": ""4d1290a1-d3a7-4fdc-9814-8bff6238dc0e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Eight"",
                    ""type"": ""Button"",
                    ""id"": ""8188c31f-4ba3-4941-a4d1-be819bd6cc6f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Nine"",
                    ""type"": ""Button"",
                    ""id"": ""88ff3fb2-6e9d-4e99-bdb9-d2cbca70730c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zero"",
                    ""type"": ""Button"",
                    ""id"": ""da1869f6-0f5f-4c36-a721-6d1d9bd6724f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionL"",
                    ""type"": ""Button"",
                    ""id"": ""bbf245a4-0e9f-4eec-aadb-90d50512ba11"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionR"",
                    ""type"": ""Button"",
                    ""id"": ""e18e0a65-6222-43bf-ba32-c33d9b885839"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""33861a05-afcf-4ca7-ac91-4f57cbb7ceb9"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""One"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2dd6663e-db88-4e59-96f6-db45c0f091b5"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Two"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a44813b9-f93e-4c1b-9778-b4daf4e584b6"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Three"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aeaf0c72-7186-4416-9d26-1d260f9f45ea"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Four"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b6bc4c4-e02d-4363-ba43-f98f5ae6035b"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Five"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbba2e36-c5ad-41f1-ac32-0c543f9689e3"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Six"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""907f086b-918c-48b0-b3c0-52eca535b387"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Seven"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fa9f5e4-f294-4435-8599-31208e1c4c4f"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Eight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85fab82c-ccf1-4a48-a976-649c15a85d6f"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12369796-0c45-46e9-9c6d-e51841babbcf"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30bfc223-c933-4b61-86e2-7d0ae9e0f0d8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70794462-3d48-4f63-a401-198109f1cd33"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ActiveBattle
        m_ActiveBattle = asset.FindActionMap("ActiveBattle", throwIfNotFound: true);
        m_ActiveBattle_One = m_ActiveBattle.FindAction("One", throwIfNotFound: true);
        m_ActiveBattle_Two = m_ActiveBattle.FindAction("Two", throwIfNotFound: true);
        m_ActiveBattle_Three = m_ActiveBattle.FindAction("Three", throwIfNotFound: true);
        m_ActiveBattle_Four = m_ActiveBattle.FindAction("Four", throwIfNotFound: true);
        m_ActiveBattle_Five = m_ActiveBattle.FindAction("Five", throwIfNotFound: true);
        m_ActiveBattle_Six = m_ActiveBattle.FindAction("Six", throwIfNotFound: true);
        m_ActiveBattle_Seven = m_ActiveBattle.FindAction("Seven", throwIfNotFound: true);
        m_ActiveBattle_Eight = m_ActiveBattle.FindAction("Eight", throwIfNotFound: true);
        m_ActiveBattle_Nine = m_ActiveBattle.FindAction("Nine", throwIfNotFound: true);
        m_ActiveBattle_Zero = m_ActiveBattle.FindAction("Zero", throwIfNotFound: true);
        m_ActiveBattle_ActionL = m_ActiveBattle.FindAction("ActionL", throwIfNotFound: true);
        m_ActiveBattle_ActionR = m_ActiveBattle.FindAction("ActionR", throwIfNotFound: true);
    }

    ~@ActiveBattleInput()
    {
        UnityEngine.Debug.Assert(!m_ActiveBattle.enabled, "This will cause a leak and performance issues, ActiveBattleInput.ActiveBattle.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ActiveBattle
    private readonly InputActionMap m_ActiveBattle;
    private List<IActiveBattleActions> m_ActiveBattleActionsCallbackInterfaces = new List<IActiveBattleActions>();
    private readonly InputAction m_ActiveBattle_One;
    private readonly InputAction m_ActiveBattle_Two;
    private readonly InputAction m_ActiveBattle_Three;
    private readonly InputAction m_ActiveBattle_Four;
    private readonly InputAction m_ActiveBattle_Five;
    private readonly InputAction m_ActiveBattle_Six;
    private readonly InputAction m_ActiveBattle_Seven;
    private readonly InputAction m_ActiveBattle_Eight;
    private readonly InputAction m_ActiveBattle_Nine;
    private readonly InputAction m_ActiveBattle_Zero;
    private readonly InputAction m_ActiveBattle_ActionL;
    private readonly InputAction m_ActiveBattle_ActionR;
    public struct ActiveBattleActions
    {
        private @ActiveBattleInput m_Wrapper;
        public ActiveBattleActions(@ActiveBattleInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @One => m_Wrapper.m_ActiveBattle_One;
        public InputAction @Two => m_Wrapper.m_ActiveBattle_Two;
        public InputAction @Three => m_Wrapper.m_ActiveBattle_Three;
        public InputAction @Four => m_Wrapper.m_ActiveBattle_Four;
        public InputAction @Five => m_Wrapper.m_ActiveBattle_Five;
        public InputAction @Six => m_Wrapper.m_ActiveBattle_Six;
        public InputAction @Seven => m_Wrapper.m_ActiveBattle_Seven;
        public InputAction @Eight => m_Wrapper.m_ActiveBattle_Eight;
        public InputAction @Nine => m_Wrapper.m_ActiveBattle_Nine;
        public InputAction @Zero => m_Wrapper.m_ActiveBattle_Zero;
        public InputAction @ActionL => m_Wrapper.m_ActiveBattle_ActionL;
        public InputAction @ActionR => m_Wrapper.m_ActiveBattle_ActionR;
        public InputActionMap Get() { return m_Wrapper.m_ActiveBattle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActiveBattleActions set) { return set.Get(); }
        public void AddCallbacks(IActiveBattleActions instance)
        {
            if (instance == null || m_Wrapper.m_ActiveBattleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ActiveBattleActionsCallbackInterfaces.Add(instance);
            @One.started += instance.OnOne;
            @One.performed += instance.OnOne;
            @One.canceled += instance.OnOne;
            @Two.started += instance.OnTwo;
            @Two.performed += instance.OnTwo;
            @Two.canceled += instance.OnTwo;
            @Three.started += instance.OnThree;
            @Three.performed += instance.OnThree;
            @Three.canceled += instance.OnThree;
            @Four.started += instance.OnFour;
            @Four.performed += instance.OnFour;
            @Four.canceled += instance.OnFour;
            @Five.started += instance.OnFive;
            @Five.performed += instance.OnFive;
            @Five.canceled += instance.OnFive;
            @Six.started += instance.OnSix;
            @Six.performed += instance.OnSix;
            @Six.canceled += instance.OnSix;
            @Seven.started += instance.OnSeven;
            @Seven.performed += instance.OnSeven;
            @Seven.canceled += instance.OnSeven;
            @Eight.started += instance.OnEight;
            @Eight.performed += instance.OnEight;
            @Eight.canceled += instance.OnEight;
            @Nine.started += instance.OnNine;
            @Nine.performed += instance.OnNine;
            @Nine.canceled += instance.OnNine;
            @Zero.started += instance.OnZero;
            @Zero.performed += instance.OnZero;
            @Zero.canceled += instance.OnZero;
            @ActionL.started += instance.OnActionL;
            @ActionL.performed += instance.OnActionL;
            @ActionL.canceled += instance.OnActionL;
            @ActionR.started += instance.OnActionR;
            @ActionR.performed += instance.OnActionR;
            @ActionR.canceled += instance.OnActionR;
        }

        private void UnregisterCallbacks(IActiveBattleActions instance)
        {
            @One.started -= instance.OnOne;
            @One.performed -= instance.OnOne;
            @One.canceled -= instance.OnOne;
            @Two.started -= instance.OnTwo;
            @Two.performed -= instance.OnTwo;
            @Two.canceled -= instance.OnTwo;
            @Three.started -= instance.OnThree;
            @Three.performed -= instance.OnThree;
            @Three.canceled -= instance.OnThree;
            @Four.started -= instance.OnFour;
            @Four.performed -= instance.OnFour;
            @Four.canceled -= instance.OnFour;
            @Five.started -= instance.OnFive;
            @Five.performed -= instance.OnFive;
            @Five.canceled -= instance.OnFive;
            @Six.started -= instance.OnSix;
            @Six.performed -= instance.OnSix;
            @Six.canceled -= instance.OnSix;
            @Seven.started -= instance.OnSeven;
            @Seven.performed -= instance.OnSeven;
            @Seven.canceled -= instance.OnSeven;
            @Eight.started -= instance.OnEight;
            @Eight.performed -= instance.OnEight;
            @Eight.canceled -= instance.OnEight;
            @Nine.started -= instance.OnNine;
            @Nine.performed -= instance.OnNine;
            @Nine.canceled -= instance.OnNine;
            @Zero.started -= instance.OnZero;
            @Zero.performed -= instance.OnZero;
            @Zero.canceled -= instance.OnZero;
            @ActionL.started -= instance.OnActionL;
            @ActionL.performed -= instance.OnActionL;
            @ActionL.canceled -= instance.OnActionL;
            @ActionR.started -= instance.OnActionR;
            @ActionR.performed -= instance.OnActionR;
            @ActionR.canceled -= instance.OnActionR;
        }

        public void RemoveCallbacks(IActiveBattleActions instance)
        {
            if (m_Wrapper.m_ActiveBattleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IActiveBattleActions instance)
        {
            foreach (var item in m_Wrapper.m_ActiveBattleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ActiveBattleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ActiveBattleActions @ActiveBattle => new ActiveBattleActions(this);
    public interface IActiveBattleActions
    {
        void OnOne(InputAction.CallbackContext context);
        void OnTwo(InputAction.CallbackContext context);
        void OnThree(InputAction.CallbackContext context);
        void OnFour(InputAction.CallbackContext context);
        void OnFive(InputAction.CallbackContext context);
        void OnSix(InputAction.CallbackContext context);
        void OnSeven(InputAction.CallbackContext context);
        void OnEight(InputAction.CallbackContext context);
        void OnNine(InputAction.CallbackContext context);
        void OnZero(InputAction.CallbackContext context);
        void OnActionL(InputAction.CallbackContext context);
        void OnActionR(InputAction.CallbackContext context);
    }
}
