//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.0
//     from Assets/Sys_PlayerTools/Scripts/ToolInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ToolInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ToolInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ToolInputActions"",
    ""maps"": [
        {
            ""name"": ""Tools"",
            ""id"": ""31f63de8-03f4-49cf-a3ae-143918a2bfbd"",
            ""actions"": [
                {
                    ""name"": ""RT"",
                    ""type"": ""Button"",
                    ""id"": ""8e230145-aaf3-4ed7-9b96-f52397fbef2c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RB"",
                    ""type"": ""Button"",
                    ""id"": ""d3f456d3-b3ae-4159-829e-5b9bd4499398"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LT"",
                    ""type"": ""Button"",
                    ""id"": ""1ace7bb2-88f7-4cda-9834-9ccf4c51bbbf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LB"",
                    ""type"": ""Button"",
                    ""id"": ""63b06c9d-ee1b-4ba2-9354-209b3e63c82a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e4eadcfb-a384-4507-90d3-1e844a5c369e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee5de2ec-f8d3-4286-a227-c89432502e28"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3c8bd50-8a2e-4772-8324-df6f406249ff"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1df62c9-8329-4642-94a5-1238ecc5753a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Tools
        m_Tools = asset.FindActionMap("Tools", throwIfNotFound: true);
        m_Tools_RT = m_Tools.FindAction("RT", throwIfNotFound: true);
        m_Tools_RB = m_Tools.FindAction("RB", throwIfNotFound: true);
        m_Tools_LT = m_Tools.FindAction("LT", throwIfNotFound: true);
        m_Tools_LB = m_Tools.FindAction("LB", throwIfNotFound: true);
    }

    ~@ToolInputActions()
    {
        UnityEngine.Debug.Assert(!m_Tools.enabled, "This will cause a leak and performance issues, ToolInputActions.Tools.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Tools
    private readonly InputActionMap m_Tools;
    private List<IToolsActions> m_ToolsActionsCallbackInterfaces = new List<IToolsActions>();
    private readonly InputAction m_Tools_RT;
    private readonly InputAction m_Tools_RB;
    private readonly InputAction m_Tools_LT;
    private readonly InputAction m_Tools_LB;
    public struct ToolsActions
    {
        private @ToolInputActions m_Wrapper;
        public ToolsActions(@ToolInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @RT => m_Wrapper.m_Tools_RT;
        public InputAction @RB => m_Wrapper.m_Tools_RB;
        public InputAction @LT => m_Wrapper.m_Tools_LT;
        public InputAction @LB => m_Wrapper.m_Tools_LB;
        public InputActionMap Get() { return m_Wrapper.m_Tools; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ToolsActions set) { return set.Get(); }
        public void AddCallbacks(IToolsActions instance)
        {
            if (instance == null || m_Wrapper.m_ToolsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ToolsActionsCallbackInterfaces.Add(instance);
            @RT.started += instance.OnRT;
            @RT.performed += instance.OnRT;
            @RT.canceled += instance.OnRT;
            @RB.started += instance.OnRB;
            @RB.performed += instance.OnRB;
            @RB.canceled += instance.OnRB;
            @LT.started += instance.OnLT;
            @LT.performed += instance.OnLT;
            @LT.canceled += instance.OnLT;
            @LB.started += instance.OnLB;
            @LB.performed += instance.OnLB;
            @LB.canceled += instance.OnLB;
        }

        private void UnregisterCallbacks(IToolsActions instance)
        {
            @RT.started -= instance.OnRT;
            @RT.performed -= instance.OnRT;
            @RT.canceled -= instance.OnRT;
            @RB.started -= instance.OnRB;
            @RB.performed -= instance.OnRB;
            @RB.canceled -= instance.OnRB;
            @LT.started -= instance.OnLT;
            @LT.performed -= instance.OnLT;
            @LT.canceled -= instance.OnLT;
            @LB.started -= instance.OnLB;
            @LB.performed -= instance.OnLB;
            @LB.canceled -= instance.OnLB;
        }

        public void RemoveCallbacks(IToolsActions instance)
        {
            if (m_Wrapper.m_ToolsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IToolsActions instance)
        {
            foreach (var item in m_Wrapper.m_ToolsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ToolsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ToolsActions @Tools => new ToolsActions(this);
    public interface IToolsActions
    {
        void OnRT(InputAction.CallbackContext context);
        void OnRB(InputAction.CallbackContext context);
        void OnLT(InputAction.CallbackContext context);
        void OnLB(InputAction.CallbackContext context);
    }
}
